=begin
#Frontend Dummy data

#No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::DefaultApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @instance = SwaggerClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instact of DefaultApi' do
      expect(@instance).to be_instance_of(SwaggerClient::DefaultApi)
    end
  end

  # unit tests for contracts_post
  # Contract page returns contracts
  # Contracts are returned based on the contract status value from {unassigned, active, completed} 
  # @param contract_status contract_status value that need to be considered for filter
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse200]
  describe 'contracts_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for root_post
  # Home page returns recent contracts and recent tours for homepage
  # Recent Contracts show the 5 most recently created and unassigned contracts. The contracts shown will be filtered according to the user&#39;s role and location.  Recent Tours shows the status of the 5 most recent tours the user has visited. It&#39;s likely the most frequently tours are the ones actively being worked on. 
  # @param user_id user_id value that need to be considered for filter
  # @param [Hash] opts the optional parameters
  # @return [InlineResponse200]
  describe 'root_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
